batch_size: 100   # batch size
epochs: 2000           # total number of epochs
eval_every_n_epochs: 1          # validation frequency
fine_tune_from: pretrained_gin  # sub directory of pre-trained model in ./ckpt
log_every_n_steps: 50           # print training log frequency
fp16_precision: False           # float precision 16 (i.e. True/False)
init_lr: 0.0001               # initial learning rate for the prediction head
init_base_lr: 0.0005            # initial learning rate for the base GNN encoder
weight_decay: 0.00005             # weight decay of Adam
gpu: cuda:0                     # training GPU
task_name: OSC # name of fine-tuning benchmark, inlcuding
                                # classifications: BBBP/BACE/ClinTox/Tox21/HIV/SIDER/MUV
                                # regressions: FreeSolv/ESOL/Lipo/qm7/qm8/qm9

model_type: gin                 # GNN backbone (i.e., gin/gcn)
model: 
  num_layer: 8   # number of graph conv layers
  
  emb_dim: 500
  feat_dim: 512                 # output feature dimention
  drop_ratio: 0.5             # dropout ratio
  pool: add

dataset:
  num_workers: 0               # dataloader number of workers
  valid_size:  0.1
  test_size:  0.1          # ratio of test data
  splitting: random  # data splitting (i.e., random/scaffold)
