name: deepacceptor
channels:
  - defaults
dependencies:
  - ca-certificates=2024.3.11
  - colorama=0.4.6
  - libffi=3.4.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.8.19
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tqdm=4.65.0

  - wheel=0.41.2
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.50.0
      - gast==0.3.3
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h5py==2.10.0
      - idna==3.6
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - joblib==1.3.2
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.5.2
      - numpy==1.18.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==1.4.3
      - pillow==10.2.0
      - protobuf==3.20.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - rdkit==2023.9.5
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-learn==1.1.2
      - scipy==1.4.1
      - six==1.16.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.3.0
      - tensorflow-estimator==2.3.0
      - termcolor==2.4.0
      - threadpoolctl==3.4.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - zipp==3.18.1
